### ISSUE TITLE
标注端，任务显示剩余6题，但是点击提示"无更多题目"

### ISSUE THREAD

**Issue by beginOfAll** [opendatalab/LabelLLM#14]
标注端，任务显示剩余6题，但是点击提示"无更多题目"
请问是什么原因导致？
![企业微信截图_fae62955-e061-4e6d-a7f8-baf2d88bd01e](https://github.com/opendatalab/LabelLLM/assets/29474786/fd3d77a0-07b3-4fe1-bd98-a88fa17d31f3)

显示的6条是否在这个标注中的22条里面，怎么继续标完？
<img width="803" alt="企业微信截图_f3aaa69a-aeef-4aad-a461-78284a93222f" src="https://github.com/opendatalab/LabelLLM/assets/29474786/3b5b47ea-1a45-4e50-8c0c-d352588bd34e">

**Comment by Hannah-cc** [comment]
1.可查看下多题的questionnaire_id是否一致，questionnaire_id指父级的题目ID，id一样会被视为同一道题目。同一道题如要求标注多遍，同一个标注员只可领取到一次

**Comment by Hannah-cc** [comment]
这个应该是有人领取了题目，没有提交，答题倒计时没结束，题目没有回收，还在那些人手上

**Comment by Hannah-cc** [comment]
第二种情况：可查看下多题的questionnaire_id是否一致，questionnaire_id指父级的题目ID，id一样会被视为同一道题目。同一道题如要求标注多遍，同一个标注员只可领取到一次
