### ISSUE TITLE
#建议#任务开始后，没办法编辑

### ISSUE THREAD

**Issue by luisxin** [opendatalab/LabelLLM#18]
任务开始后，在标注过程中，会发现一些配置需要调整，比如标注时间太短，选项不需要必填这些。
目前不支持对进行中的任务进行标注，必需删除了重新来，这样导致标注一半的任务也只能重新做。
![Uploading image.png…]()

**Comment by Hannah-cc** [comment]
建议预览没问题后再开始任务
![image](https://github.com/user-attachments/assets/d83b540b-7c2c-4fe8-b943-9c9e2f69b4ae)

**Comment by luisxin** [comment]
了解，但使用中是标注员在标注数据的过程中，会反馈有的配置不合理，预览的时候没办法避免。
