### ISSUE TITLE
有抽检功能嘛？

### ISSUE THREAD

**Issue by interstate50** [opendatalab/LabelLLM#19]
现在已有的“打回重做”太粗暴了，会更新查看标注结果，然后看情况进行逐个问题的打回这种功能嘛?

**Comment by luisxin** [comment]
发现一个问题，好像看不到标注结果 ？？
![image](https://github.com/user-attachments/assets/3098fd91-24d1-4d79-bb36-d31cb4bd7ac1)
![image](https://github.com/user-attachments/assets/96b17af7-a21f-44e0-8d0a-83f3d937aff1)

**Comment by Hannah-cc** [comment]
第二题是有标注结果的，第一题看上去是没有标注

> 发现一个问题，好像看不到标注结果 ？？ ![image](https://private-user-images.githubusercontent.com/16147110/350332940-3098fd91-24d1-4d79-bb36-d31cb4bd7ac1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MTcyMTMsIm5iZiI6MTcyMTYxNjkxMywicGF0aCI6Ii8xNjE0NzExMC8zNTAzMzI5NDAtMzA5OGZkOTEtMjRkMS00ZDc5LWJiMzYtZDMxY2I0YmQ3YWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDAyNTUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjY2FjNDFiOTc0NDE3NDAwYzVmOGE3NjBhYjJjZjIwMGNlNmQzMzY2MDkxNmU5YjM3ZDkyOWE2ZWQzZWY3ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ae_hApaycT2Ba5s018kehhe2gGOaC5aNfOwYunj2_9E) ![image](https://private-user-images.githubusercontent.com/16147110/350333235-96b17af7-a21f-44e0-8d0a-83f3d937aff1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MTcyMTMsIm5iZiI6MTcyMTYxNjkxMywicGF0aCI6Ii8xNjE0NzExMC8zNTAzMzMyMzUtOTZiMTdhZjctYTIxZi00NGUwLThkMGEtODNmM2Q5MzdhZmYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDAyNTUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMGEyMDJiYjQyMWM4M2VlY2I3NTcwM2MwZjNmM2M5MjczMzhhYjg0ODViYzZkN2U2MTQ0NTI5MTE0ZmY5MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EAZbgUsG_R84DTmuz8pAorpjevCNcK9vpyCG-InDxDk)

**Comment by Hannah-cc** [comment]
> 现在已有的“打回重做”太粗暴了，会更新查看标注结果，然后看情况进行逐个问题的打回这种功能嘛?

规划中~
