### ISSUE TITLE
docker-compose指定多mongo版本问题

### ISSUE THREAD

**Issue by EvilCalf** [opendatalab/LabelLLM#29]
unsupported WiredTiger file version: this build only supports versions up to 4, and the file is version 5: WT_ERROR: non-specific WiredTiger error Raw: [1724146121:215540][1:0x7fb2d5457b00], connection: __log_open_verify, 925: unsupported WiredTiger file version: this build only supports versions up to 4, and the file is version 5: WT_ERROR: non-specific WiredTiger error

**Comment by lacia-hIE** [comment]
以下是一个建议

更新 Docker Compose文件

```
mongo:
  image: mongo:5.0
```

删除现有数据卷(这将删除所有数据)：

`docker-compose down -v`

然后重新启动服务：

`docker-compose up`
