### ISSUE TITLE
后端启动不起来

### ISSUE THREAD

**Issue by Tomcat099** [opendatalab/LabelLLM#4]
我在docker启动后端的几个，都启动不成功，是什么原因呢？有没有可以解答下的？
![屏幕截图 2024-06-15 195216](https://github.com/opendatalab/LabelLLM/assets/149558902/54911fe7-d9e9-4db2-9392-c519262ede30)

**Comment by luxuncang** [comment]
需要 labellm-backend 的日志 
![0eba2cd0-1c58-4c3c-9ee3-59b274688832](https://github.com/opendatalab/LabelLLM/assets/70730964/ef97b8f3-99e3-4feb-aa74-57dc9aed54c9)

可以先参考 [常见问题](https://github.com/opendatalab/LabelLLM/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

**Comment by fenglvming** [comment]
2024-07-14 09:14:38 /app/scripts/start.sh: 4: Syntax error: "elif" unexpected (expecting "then")
2024-07-14 09:15:40 /app/scripts/start.sh: 4: Syntax error: "elif" unexpected (expecting "then")
