### ISSUE TITLE
标注员只能看到部分数据

### ISSUE THREAD

**Issue by yangyazhou97** [opendatalab/LabelLLM#7]
总共有4条待打标数据，分配给标注团队（只有一名标注员）后，标注员只能看到一条数据，标注员不应该看到分配给他的全部数据吗？
![image](https://github.com/opendatalab/LabelLLM/assets/89854398/dcbf6e4e-c7e7-434a-9aa3-0677c1832905)
![image](https://github.com/opendatalab/LabelLLM/assets/89854398/0719bb6a-0ab0-4819-a923-76ad96514f58)

**Comment by Hannah-cc** [comment]
可查看下多题的questionnaire_id是否一致，questionnaire_id指父级的题目ID，id一样会被视为同一道题目。同一道题如要求标注多遍，同一个标注员只可领取到一次

**Comment by yangyazhou97** [comment]
嗯嗯 已经解决了，谢谢
